/**
 * Error code enumerations per draft-14 §13.1.
 * Each error code namespace is a separate enum for type safety.
 */

/** Session Termination Error Codes (§13.1.1, Table 8) */
export enum SessionTerminationError {
  NO_ERROR = 0x0,
  INTERNAL_ERROR = 0x1,
  UNAUTHORIZED = 0x2,
  PROTOCOL_VIOLATION = 0x3,
  INVALID_REQUEST_ID = 0x4,
  DUPLICATE_TRACK_ALIAS = 0x5,
  KEY_VALUE_FORMATTING_ERROR = 0x6,
  TOO_MANY_REQUESTS = 0x7,
  INVALID_PATH = 0x8,
  MALFORMED_PATH = 0x9,
  GOAWAY_TIMEOUT = 0x10,
  CONTROL_MESSAGE_TIMEOUT = 0x11,
  DATA_STREAM_TIMEOUT = 0x12,
  AUTH_TOKEN_CACHE_OVERFLOW = 0x13,
  DUPLICATE_AUTH_TOKEN_ALIAS = 0x14,
  VERSION_NEGOTIATION_FAILED = 0x15,
  MALFORMED_AUTH_TOKEN = 0x16,
  UNKNOWN_AUTH_TOKEN_ALIAS = 0x17,
  EXPIRED_AUTH_TOKEN = 0x18,
  INVALID_AUTHORITY = 0x19,
  MALFORMED_AUTHORITY = 0x1a,
}

/** SUBSCRIBE_ERROR Codes (§13.1.2, Table 9) */
export enum SubscribeErrorCode {
  INTERNAL_ERROR = 0x0,
  UNAUTHORIZED = 0x1,
  TIMEOUT = 0x2,
  NOT_SUPPORTED = 0x3,
  TRACK_DOES_NOT_EXIST = 0x4,
  INVALID_RANGE = 0x5,
  MALFORMED_AUTH_TOKEN = 0x10,
  EXPIRED_AUTH_TOKEN = 0x12,
}

/** PUBLISH_DONE Status Codes (§13.1.3, Table 10) */
export enum PublishDoneCode {
  INTERNAL_ERROR = 0x0,
  UNAUTHORIZED = 0x1,
  TRACK_ENDED = 0x2,
  SUBSCRIPTION_ENDED = 0x3,
  GOING_AWAY = 0x4,
  EXPIRED = 0x5,
  TOO_FAR_BEHIND = 0x6,
  MALFORMED_TRACK = 0x7,
}

/** PUBLISH_ERROR Codes (§13.1.4, Table 11) */
export enum PublishErrorCode {
  INTERNAL_ERROR = 0x0,
  UNAUTHORIZED = 0x1,
  TIMEOUT = 0x2,
  NOT_SUPPORTED = 0x3,
  UNINTERESTED = 0x4,
}

/** FETCH_ERROR Codes (§13.1.5, Table 12) */
export enum FetchErrorCode {
  INTERNAL_ERROR = 0x0,
  UNAUTHORIZED = 0x1,
  TIMEOUT = 0x2,
  NOT_SUPPORTED = 0x3,
  TRACK_DOES_NOT_EXIST = 0x4,
  INVALID_RANGE = 0x5,
  NO_OBJECTS = 0x6,
  INVALID_JOINING_REQUEST_ID = 0x7,
  UNKNOWN_STATUS_IN_RANGE = 0x8,
  MALFORMED_TRACK = 0x9,
  MALFORMED_AUTH_TOKEN = 0x10,
  EXPIRED_AUTH_TOKEN = 0x12,
}

/** ANNOUNCE_ERROR / PUBLISH_NAMESPACE_ERROR Codes (§13.1.6, Table 13) */
export enum AnnounceErrorCode {
  INTERNAL_ERROR = 0x0,
  UNAUTHORIZED = 0x1,
  TIMEOUT = 0x2,
  NOT_SUPPORTED = 0x3,
  UNINTERESTED = 0x4,
  MALFORMED_AUTH_TOKEN = 0x10,
  EXPIRED_AUTH_TOKEN = 0x12,
}

/** SUBSCRIBE_NAMESPACE_ERROR Codes (§13.1.7, Table 14) */
export enum SubscribeNamespaceErrorCode {
  INTERNAL_ERROR = 0x0,
  UNAUTHORIZED = 0x1,
  TIMEOUT = 0x2,
  NOT_SUPPORTED = 0x3,
  NAMESPACE_PREFIX_UNKNOWN = 0x4,
  NAMESPACE_PREFIX_OVERLAP = 0x5,
  MALFORMED_AUTH_TOKEN = 0x10,
  EXPIRED_AUTH_TOKEN = 0x12,
}

/** Data Stream Reset Error Codes (§13.1.8, Table 15) */
export enum DataStreamResetError {
  INTERNAL_ERROR = 0x0,
  CANCELLED = 0x1,
  DELIVERY_TIMEOUT = 0x2,
  SESSION_CLOSED = 0x3,
}
